tasks:
  - name: aws-cli
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT

      # ✅ Create credentials/config files for AWS CLI
      mkdir -p ~/.aws

      echo "[default]" > ~/.aws/credentials
      echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
      echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials

      echo "[default]" > ~/.aws/config
      echo "region=${AWS_DEFAULT_REGION:-us-east-1}" >> ~/.aws/config

      # ✅ Validate setup
      aws sts get-caller-identity